# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ba2fab1c22d6b4110af390382b3cb5ee32a085f18d30e5160c79ece7205676f1c78d50d40e7514a06643aebaa496a77f864e001cd65c2c8a1ba93b2526709e6

test:
  secret_key_base: 2736b706cea5ea01d9cf4ce6ef93e7d604995f712953fd2cc038e18689ca5bdf53ce4ec2616dd210a899e4e4d6cd5e279b7baddc60baedc28d2fff59a57e6ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
